### Get User By ID
GET http://localhost:8080/api/user/2
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdXRob3JpemVkIjp0cnVlLCJleHAiOjE2MzIyMzU0OTAsImlkIjoyLCJpc3MiOjIsInVzZXIiOiJpcEBnbWFpbC5jb20ifQ.g7EITh3ZgpaTcYlKYSzbWoB3AA_Z-m_znMb7TTBFjSM

### Create User 
POST http://localhost:8080/api/user
Content-Type: application/json

{
  "firtsname": "Jhon",
  "lastname": "Doe",
  "email": "jdr@gmail.com",
  "status": "ACTIVE",
  "password": "12345678"
}

### Update User 
PUT http://localhost:8080/api/user/4
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdXRob3JpemVkIjp0cnVlLCJleHAiOjE2MzIyMzU1NDksImlkIjo0LCJpc3MiOjQsInVzZXIiOiJqZHJAZ21haWwuY29tIn0.jdi0E4vU0U8vA7Q3sqQIW9wOjBMaHFlXceDB7M6sn7s

{
  "id": 4,
  "firtsname": "Jhonathan",
  "lastname": "Doe",
  "email": "jde@gmail.com",
  "status": "ACTIVE",
  "password": "12345678"
}

### Delete User By ID
DELETE http://localhost:8080/api/user/4
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdXRob3JpemVkIjp0cnVlLCJleHAiOjE2MzIyMzU1NDksImlkIjo0LCJpc3MiOjQsInVzZXIiOiJqZHJAZ21haWwuY29tIn0.jdi0E4vU0U8vA7Q3sqQIW9wOjBMaHFlXceDB7M6sn7s

### Login Request
POST http://localhost:8080/api/login
Content-Type: application/json 

{
  "email": "jdr@gmail.com",
  "password": "12345678"
}